# Generated by Django 2.2.6 on 2019-10-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_diretor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_gestor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_servidor',
        ),
    ]
