# Generated by Django 2.2.6 on 2019-11-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191030_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='imagem',
            field=models.ImageField(null=True, upload_to='media/uploads/', verbose_name='Foto do Veículo'),
        ),
    ]
