# Generated by Django 2.2.6 on 2019-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='imagem',
            field=models.ImageField(null=True, upload_to='uploads/car', verbose_name='Foto do Veículo'),
        ),
    ]
