# Generated by Django 2.2.6 on 2019-11-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191108_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/car', verbose_name='Foto do Veículo'),
        ),
    ]
