# Generated by Django 2.2.6 on 2019-11-08 13:51

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191108_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[api.validators.validate_CPF]),
        ),
        migrations.AddField(
            model_name='user',
            name='funcao',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
