# Generated by Django 2.2.6 on 2019-11-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_passenger_solicitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Passageiro', 'verbose_name_plural': 'Passageiros'},
        ),
        migrations.AlterModelOptions(
            name='solicitation',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
