# Generated by Django 2.2.6 on 2019-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191111_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='status',
            field=models.CharField(choices=[('autorizado', 'Autorizado'), ('nao_autorizado', 'Não Autorizado')], default='autorizado', max_length=30),
        ),
    ]
