# Generated by Django 2.2.6 on 2019-11-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_solicitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(blank=True, choices=[('autorizado', 'Autorizado'), ('nao_autorizado', 'Não Autorizado')], default='autorizado', max_length=30, null=True),
        ),
    ]
