# Generated by Django 2.2.6 on 2019-11-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191111_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('autorizado', 'Autorizado'), ('nao_autorizado', 'Não Autorizado')], default='solicitado', max_length=30),
        ),
    ]
