# Generated by Django 2.2.6 on 2019-11-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191111_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField()),
                ('dthrautorizacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('analise', 'Em Análise'), ('autorizado', 'Autorizado'), ('nao_autorizado', 'Não Autorizado')], default='analise', max_length=30)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Solicitation')),
                ('user_autorizador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorização',
                'verbose_name_plural': 'Autorizações',
            },
        ),
    ]
