# Generated by Django 2.2.6 on 2019-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191111_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitation',
            options={'ordering': ['-status'], 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.RemoveField(
            model_name='autorization',
            name='status',
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(blank=True, choices=[('solicitado', 'Solicitado'), ('autorizado', 'Autorizado'), ('nao_autorizado', 'Não Autorizado')], max_length=30, null=True),
        ),
    ]
