# Generated by Django 2.2.6 on 2019-11-12 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191111_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorization',
            name='dthrautorizacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Autorizado em'),
        ),
        migrations.AlterField(
            model_name='autorization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='dthrrequisicao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Solicitado em'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='dthrretorno',
            field=models.DateTimeField(verbose_name='Data do Retorno'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='dthrsaida',
            field=models.DateTimeField(verbose_name='Data da Saída'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='passageiros',
            field=models.ManyToManyField(to='api.Passenger', verbose_name='Passageiros'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(blank=True, choices=[('solicitado', 'Solicitado'), ('autorizado', 'Autorizado'), ('nao_autorizado', 'Não Autorizado')], max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nome'),
        ),
    ]
