# Generated by Django 2.2.6 on 2019-11-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191111_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('autorizado', 'Autorizado'), ('nao_autorizado', 'Não Autorizado')], default='solicitado', max_length=30, verbose_name='Status'),
        ),
    ]
