# Generated by Django 2.2.6 on 2019-11-12 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191111_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorization',
            name='user_autorizador',
        ),
        migrations.AddField(
            model_name='autorization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por'),
        ),
    ]
