# Generated by Django 2.2.6 on 2019-11-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191111_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica que este usuário tem acesso a área administrativa', verbose_name='Staff'),
        ),
    ]
