# Generated by Django 2.2.6 on 2019-11-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191112_0047'),
        ('api', '0020_auto_20191112_1028'),
    ]

    operations = [
    ]
