# Generated by Django 2.2.6 on 2019-11-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191111_2324'),
        ('api', '0023_merge_20191112_1040'),
    ]

    operations = [
    ]
